---
title: "Mini-Project 2"
authors: "Margaret Perry, Kendra Swanson, Arielle Dror"
date: "March 24, 2017"
output: html_document
---


##Goal
The goal of this code is to tidy and graph the data to display the corrolations between the cortributions and the success of the candidate. We're focusing just on general House elections.

```{r, include=FALSE}
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r}
##Renaming columns for clarity and easier join
names(contributions)[names(contributions)=="name"] <- "cmte_name"

house_elections <- house_elections %>%
  mutate(candidate_name = toupper(candidate_name))
```

```{r}
## Function that produces candidate information by state and office in 2012 election cycle

office_state_cands <- function(office_arg, state_arg) {
  filter(candidates, cand_office == office_arg, cand_election_yr == "2012", cand_office_state == state_arg)
}

## Examples (delete/comment out in final submission)
CA_house <- office_state_cands(office_arg = "H", state_arg = "CA")
CA_house

pres_cands <- office_state_cands(office_arg = "P", state_arg = "US")
pres_cands

```

```{r}
## Functions that total COMMITTEE contributions for and contributions against each candidate
## in a given table of candidates. 

cand_for <- function(data_arg) {
  data_arg %>%
    left_join(contributions, by = "cand_id") %>%
    filter(transaction_amt > 0, transaction_type == "24K" | transaction_type == "24E" | transaction_type == "24F" | transaction_type == "24C" | transaction_type == "24Z") %>%
    group_by(cand_name) %>%
    summarize(total_for = sum(transaction_amt))
}

cand_against <- function(data_arg) {
  data_arg %>%
    left_join(contributions, by = "cand_id") %>%
    filter(transaction_amt > 0, transaction_type == "24A" | transaction_type == "24N") %>%
    group_by(cand_name) %>%
    summarize(total_against = sum(transaction_amt))
}


## Examples
CA_house_cand_for <- cand_for(data_arg = CA_house)
CA_house_cand_for

CA_house_cand_against <- cand_against(data_arg = CA_house)
CA_house_cand_against

```
Transaction codes: 24A, 24N = against; 24E, 24F, 24C, 24K, 24Z = for

```{r}
## Function that determines whether a candidate has won or lost given a table of candidates
## **Note: only works for house elections** 
cand_success <- function(data_arg) {
  data_arg %>%
    left_join(house_elections, by = c("cand_id" = "fec_id")) %>%
    select(cand_name, primary_votes, general_votes, ge_winner)
}
cand_success(data_arg = office_state_cands(office_arg = "H", state_arg = "CA"))

```


```{r}
## Function that joins for, against, success, and candidates table given a table of candidates
cand_info <- function(cand_table) {
  cand_table %>%
    left_join(cand_for(data_arg = cand_table), by = "cand_name") %>%
    full_join(cand_against(data_arg = cand_table), by = "cand_name") %>%
    left_join(cand_success(data_arg = cand_table), by = "cand_name") %>%
    mutate(total = ifelse(!is.na(total_against) & !is.na(total_for), total_for + total_against, 
                          ifelse(is.na(total_against), total_for, 
                                 ifelse(is.na(total_for), total_against, 0)))) %>%
    mutate(prop_against=(total_against/total)*100) %>%
    filter(total_for > 0 & total_against > 0 & general_votes > 0) %>%
    select(cand_id, cand_name, cand_party_affiliation, cand_state, cand_office, cand_office_district, total_for, total_against, total, general_votes, ge_winner, prop_against) %>%
  arrange((cand_office_district))
}


CA_house_cand_info <- cand_info(cand_table = office_state_cands(office_arg = "H", state_arg = "CA"))

CA_house_cand_info
```

```{r}
candidate_graphic_1 <- ggplot(CA_house_cand_info, aes(x=cand_name, y= total, fill=prop_against))+coord_flip()+geom_bar(stat="identity")+scale_fill_continuous(name= "Percentage of Donations\nAgainst Candidate", low="firebrick1", high = "firebrick4")+xlab("Candidate")+ylab("Total Donations")+scale_y_continuous(breaks = c(0, 2000000, 4000000, 6000000), labels = c("$0", "$2,000,000", "$4,000,000", "$6,000,000") ) + ggtitle("House Candidates in California with\nDonations For and Against")

candidate_graphic_1
```
```{r}
candidate_graphic_2 <- ggplot(CA_house_cand_info, aes(x=cand_name, y= total, fill=ge_winner))+coord_flip()+geom_bar(stat="identity")+xlab("Candidate")+ylab("Total Donations")+scale_y_continuous(breaks = c(0, 2000000, 4000000, 6000000), labels = c("$0", "$2,000,000", "$4,000,000", "$6,000,000") ) + scale_fill_discrete("Result", breaks=c("N", "W"), labels=c("Loss", "Win"))+ggtitle("Results of Elections of House Candidates")
candidate_graphic_2
```
